import type { Instrument } from "./types";
import type { SampleManifest } from "./SampleBank";

/** Visible diagnostic marker for physical-device validation. */
export const SAMPLE_BANK_RELEASE = "Timbres gravados · build 2026-08-23.1";

type SamplePoint = {
  fileStem: string;
  midi: number;
};

const pianoPoints: SamplePoint[] = [
  { fileStem: "a0", midi: 21 },
  { fileStem: "ds1", midi: 27 },
  { fileStem: "a1", midi: 33 },
  { fileStem: "ds2", midi: 39 },
  { fileStem: "a2", midi: 45 },
  { fileStem: "ds3", midi: 51 },
  { fileStem: "a3", midi: 57 },
  { fileStem: "ds4", midi: 63 },
  { fileStem: "a4", midi: 69 },
  { fileStem: "ds5", midi: 75 },
  { fileStem: "a5", midi: 81 },
  { fileStem: "ds6", midi: 87 },
  { fileStem: "a6", midi: 93 },
  { fileStem: "ds7", midi: 99 },
  { fileStem: "a7", midi: 105 },
  { fileStem: "c8", midi: 108 }
];

const guitarPoints: SamplePoint[] = [
  { fileStem: "db2", midi: 37 },
  { fileStem: "e2", midi: 40 },
  { fileStem: "gb2", midi: 42 },
  { fileStem: "a2", midi: 45 },
  { fileStem: "c3", midi: 48 },
  { fileStem: "eb3", midi: 51 },
  { fileStem: "gb3", midi: 54 },
  { fileStem: "a3", midi: 57 },
  { fileStem: "eb4", midi: 63 },
  { fileStem: "gb4", midi: 66 },
  { fileStem: "a4", midi: 69 },
  { fileStem: "c5", midi: 72 },
  { fileStem: "eb5", midi: 75 },
  { fileStem: "gb5", midi: 78 },
  { fileStem: "a5", midi: 81 },
  { fileStem: "c6", midi: 84 }
];

// Production uses the generated JavaScript file as the reference point. This
// resolves to the app-bundled `player/audio` folder on iPhone, with no network.
const sampleBaseUrl = import.meta.env.PROD
  ? new URL("../audio/samples/", import.meta.url).toString()
  : "/audio/samples/";

const velocityLayers = (directory: string, points: SamplePoint[]) => points.flatMap(({ fileStem, midi }) => [
  {
    url: `${sampleBaseUrl}${directory}/${fileStem}-soft.m4a`,
    midi,
    minVelocity: 0,
    maxVelocity: 0.55
  },
  {
    url: `${sampleBaseUrl}${directory}/${fileStem}-loud.m4a`,
    midi,
    minVelocity: 0.55,
    maxVelocity: 1
  }
]);

/** Locally bundled, free-to-distribute instruments. Files are generated by
 * scripts/prepare-free-audio-samples.sh and deliberately never fetched from a CDN. */
export const LOCAL_SAMPLE_MANIFESTS: Record<Instrument, SampleManifest> = {
  piano: {
    instrument: "piano",
    attribution: "Piano: Salamander Grand Piano V3 by Alexander Holm, CC BY 3.0.",
    envelope: { attackSeconds: 0.008, releaseSeconds: 0.11, maxTailSeconds: 0.18 },
    samples: velocityLayers("piano", pianoPoints)
  },
  guitar: {
    instrument: "guitar",
    attribution: "Violão: Shinyguitar by Karoryfer Lecolds, CC0 1.0.",
    envelope: { attackSeconds: 0.004, releaseSeconds: 0.08, maxTailSeconds: 0.12 },
    samples: velocityLayers("guitar", guitarPoints)
  }
};
