import { constants as fileSystemConstants } from "node:fs";
import fs from "node:fs/promises";
import path from "node:path";
import { nanoid } from "nanoid";
import { paths } from "../config/env.js";
import { AppError } from "../errors/AppError.js";
import { extensionOf } from "../utils/filenames.js";

export class FileStorageService {
  constructor(private baseUploadsDir = paths.uploadsDir, private baseExportsDir = paths.exportsDir) {}

  async ensureDirectories(): Promise<void> {
    await fs.mkdir(this.baseUploadsDir, { recursive: true, mode: 0o700 });
    await fs.mkdir(this.baseExportsDir, { recursive: true, mode: 0o700 });
  }

  generateStoredFilename(originalFilename: string): string {
    const ext = extensionOf(originalFilename);
    if (!ext) throw new AppError(400, "Arquivo sem extensão válida.", "INVALID_EXTENSION");
    return `${nanoid(32)}.${ext}`;
  }

  generateExportStoredFilename(scoreId: string): string {
    return `${scoreId}-${nanoid(12)}.musicxml`;
  }

  async saveUpload(storedFilename: string, buffer: Buffer): Promise<void> {
    await this.ensureDirectories();
    await fs.writeFile(this.resolveUploadPath(storedFilename), buffer, { mode: 0o600, flag: "wx" });
  }

  async saveExport(storedFilename: string, content: string): Promise<void> {
    await this.ensureDirectories();
    await fs.writeFile(this.resolveExportPath(storedFilename), content, { mode: 0o600, flag: "wx" });
  }

  async readExport(storedFilename: string): Promise<string> {
    return fs.readFile(this.resolveExportPath(storedFilename), "utf8");
  }

  /**
   * Reads an export from one already-open, non-symlinked regular file. This
   * avoids exposing filesystem paths and prevents a file from being swapped
   * between validation and the download response.
   */
  async readExportForDownload(storedFilename: string): Promise<Buffer> {
    const exportPath = this.resolveExportPath(storedFilename);
    const handle = await fs.open(exportPath, fileSystemConstants.O_RDONLY | fileSystemConstants.O_NOFOLLOW);
    try {
      const details = await handle.stat();
      if (!details.isFile()) {
        const error = new Error("MusicXML export is not a regular file.");
        (error as NodeJS.ErrnoException).code = "EXPORT_NOT_A_FILE";
        throw error;
      }
      return await handle.readFile();
    } finally {
      await handle.close();
    }
  }

  /** Checks availability without reading the export into memory. */
  async isReadableExport(storedFilename: string): Promise<boolean> {
    const exportPath = this.resolveExportPath(storedFilename);
    try {
      const handle = await fs.open(exportPath, fileSystemConstants.O_RDONLY | fileSystemConstants.O_NOFOLLOW);
      try {
        const details = await handle.stat();
        return details.isFile();
      } finally {
        await handle.close();
      }
    } catch {
      return false;
    }
  }

  async deleteUpload(storedFilename: string): Promise<void> {
    await fs.rm(this.resolveUploadPath(storedFilename), { force: true });
  }

  async deleteExport(storedFilename: string | null): Promise<void> {
    if (storedFilename) await fs.rm(this.resolveExportPath(storedFilename), { force: true });
  }

  resolveUploadPath(storedFilename: string): string {
    return this.safeJoin(this.baseUploadsDir, storedFilename);
  }

  resolveExportPath(storedFilename: string): string {
    return this.safeJoin(this.baseExportsDir, storedFilename);
  }

  private safeJoin(baseDir: string, filename: string): string {
    // Critical: only internal filenames generated by the server can become paths.
    if (!/^[a-zA-Z0-9_-]+\.[a-zA-Z0-9]+$/.test(filename)) {
      throw new AppError(400, "Nome interno de arquivo inválido.", "INVALID_STORED_FILENAME");
    }
    const resolved = path.resolve(baseDir, filename);
    const base = path.resolve(baseDir);
    if (!resolved.startsWith(`${base}${path.sep}`)) {
      throw new AppError(400, "Caminho de arquivo inválido.", "PATH_TRAVERSAL_BLOCKED");
    }
    return resolved;
  }
}
