import fs from "node:fs/promises";
import path from "node:path";
import { nanoid } from "nanoid";
import { paths } from "../config/env.js";
import { AppError } from "../errors/AppError.js";
import { extensionOf } from "../utils/filenames.js";

export class FileStorageService {
  constructor(private baseUploadsDir = paths.uploadsDir, private baseExportsDir = paths.exportsDir) {}

  async ensureDirectories(): Promise<void> {
    await fs.mkdir(this.baseUploadsDir, { recursive: true, mode: 0o700 });
    await fs.mkdir(this.baseExportsDir, { recursive: true, mode: 0o700 });
  }

  generateStoredFilename(originalFilename: string): string {
    const ext = extensionOf(originalFilename);
    if (!ext) throw new AppError(400, "Arquivo sem extensão válida.", "INVALID_EXTENSION");
    return `${nanoid(32)}.${ext}`;
  }

  generateExportStoredFilename(scoreId: string): string {
    return `${scoreId}-${nanoid(12)}.musicxml`;
  }

  async saveUpload(storedFilename: string, buffer: Buffer): Promise<void> {
    await this.ensureDirectories();
    await fs.writeFile(this.resolveUploadPath(storedFilename), buffer, { mode: 0o600, flag: "wx" });
  }

  async saveExport(storedFilename: string, content: string): Promise<void> {
    await this.ensureDirectories();
    await fs.writeFile(this.resolveExportPath(storedFilename), content, { mode: 0o600, flag: "wx" });
  }

  async deleteUpload(storedFilename: string): Promise<void> {
    await fs.rm(this.resolveUploadPath(storedFilename), { force: true });
  }

  async deleteExport(storedFilename: string | null): Promise<void> {
    if (storedFilename) await fs.rm(this.resolveExportPath(storedFilename), { force: true });
  }

  resolveUploadPath(storedFilename: string): string {
    return this.safeJoin(this.baseUploadsDir, storedFilename);
  }

  resolveExportPath(storedFilename: string): string {
    return this.safeJoin(this.baseExportsDir, storedFilename);
  }

  private safeJoin(baseDir: string, filename: string): string {
    // Critical: only internal filenames generated by the server can become paths.
    if (!/^[a-zA-Z0-9_-]+\.[a-zA-Z0-9]+$/.test(filename)) {
      throw new AppError(400, "Nome interno de arquivo inválido.", "INVALID_STORED_FILENAME");
    }
    const resolved = path.resolve(baseDir, filename);
    const base = path.resolve(baseDir);
    if (!resolved.startsWith(`${base}${path.sep}`)) {
      throw new AppError(400, "Caminho de arquivo inválido.", "PATH_TRAVERSAL_BLOCKED");
    }
    return resolved;
  }
}
